
% MATLAB Code from Radar Waveform Analyzer App

% Generated by MATLAB 24.2 and Phased Array System Toolbox 24.2

% Generated on 28-Feb-2025 00:53:09

% Create a Rectangular Waveform object
Waveform = phased.RectangularWaveform('SampleRate',6e+06,...
'PulseWidth',3.33333e-07,'PRF',30000,'NumPulses',1,'FrequencyOffset',0);
Fs = Waveform.SampleRate;
% Call step method of Waveform to generate IQ samples of Waveform
x = Waveform();
% Create figure for Real and Imaginary
figure;
l = (0:length(x)-1)/Fs;
subplot(2,1,1);
[~, scale, ~] = engunits(l(end));
l = l*scale;
plot(l,real(x));
axis([-0.14681 38.4384 -0.080886 1.242]);
xlabel('');
ylabel('Amplitude: Real Part (V)');
grid on;
subplot(2,1,2);
plot(l,imag(x));
axis([-0.14681 38.4384 -0.1 0.1]);
xlabel('Time (µs)');
ylabel('Amplitude: Imaginary Part (V)');
grid on;

% Create figure for Spectrum
figure;
pwelch(x, [], [], [], Fs, 'centered');
xlabel('Frequency (MHz)');
ylabel('Power/Frequency (dB/Hz)');
title('Power Spectral Density of Baseband Signal');

% Create figure for Ambiguity Function Contour
figure;
prf = Waveform.PRF;
ambgfun(x,Fs,prf);
axis([-0.44926 0.6331 -1.4724 -1.3747]);
xlabel('Delay {\tau} (µs)');
ylabel('Doppler {f}_{d} (MHz)');
title('Ambiguity Function');

% Create a Matched Filter object
coeff = getMatchedFilter(Waveform);
Compression = phased.MatchedFilter('Coefficients',coeff(:,1), ...
'SpectrumWindow','None');
y = Compression(x);
